### ISSUE TITLE
Not work on macOS Ventura 

### ISSUE THREAD

**Issue by lifesign** [Frostplexx/obisdian-mac-touchbar#2]
macOS version: 13.4.1
when added item, not show on my touchbar. still shows the f{x} function keys

**Comment by frostplexx** [comment]
Could you make sure that the plugin is enabled and then restart Obsidian?

**Comment by lifesign** [comment]
enabled and also restarted. Nothing changed, still the function keys


<img width="809" alt="SCR-20230822-myky" src="https://github.com/Frostplexx/obsidian-touchbar-macros/assets/2189610/90038a84-c97f-4f48-9c84-031739758713">

<img width="806" alt="SCR-20230822-mymz" src="https://github.com/Frostplexx/obsidian-touchbar-macros/assets/2189610/f9d8265d-da63-4862-99e9-1faffdec6d65">



![WechatIMG507](https://github.com/Frostplexx/obsidian-touchbar-macros/assets/2189610/f95460b5-523e-4005-b276-2214284d9fb4)

**Comment by frostplexx** [comment]
From the pictures you sent it looks like you set your Touch Bar to always show the F-Keys (see my screenshot). If you enable this setting macOS won't show you any Touch Bar items from Apps. You need to set your Touch Bar to show "App Controls". You can still access the F-Keys when pressing and holding the fn Button.

<img width="538" alt="image" src="https://github.com/Frostplexx/obsidian-touchbar-macros/assets/62436912/955c43bf-9ef0-4721-a103-b8d5b0c4c3af">

**Comment by lifesign** [comment]
thx. it works~
